# Generated by Django 4.0.6 on 2022-07-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопросы')),
                ('answer', models.TextField(verbose_name='Ответы')),
            ],
            options={
                'verbose_name': 'Вопросы',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
