# Generated by Django 4.0.6 on 2022-08-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdd',
            name='correctNumber',
            field=models.TextField(default=0, verbose_name='Цифра ответа'),
            preserve_default=False,
        ),
    ]
